# Generated by Django 4.0 on 2021-12-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('continent_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('continent_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('region_code', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
